import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.Head}>
        <nav>
          <a href='/'> Home</a>
          <a href='/about-us'> About Us</a>
          <a href='/events'> Events</a>
          <a href=''> Events</a>
        </nav>
      </header>

      <main className={styles.main}>
        <a href=''>
          <div>
            <h2>New Prompts:</h2>
            <p>placeholder</p>

          </div>
        </a>


      </main>

      <footer className={styles.footer}></footer>
    </>
  )
}
